
version: "3"

services:
  apache:
    image: hfe-apache
    ports:
    - "80:80"
    networks:
    - webproxy

  tomcat:
    image: hfe-tomcat
    environment:
      - hostname=spring
    networks:
    - webproxy
    depends_on:
      - spring

  spring:
    image: hfe-spring
    networks:
    - webproxy

networks:
  webproxy:
    driver: bridge
